fn main() {
    generate_language_models();
    tauri_build::build();
}

fn generate_language_models() {
    use std::io::Write as _;

    println!("cargo:rerun-if-changed=../corpus/ru.txt");
    println!("cargo:rerun-if-changed=../corpus/en.txt");
    println!("cargo:rerun-if-changed=../corpus/ua.txt");

    let ru_text = std::fs::read_to_string("../corpus/ru.txt").unwrap_or_default();
    let en_text = std::fs::read_to_string("../corpus/en.txt").unwrap_or_default();
    let ua_text = std::fs::read_to_string("../corpus/ua.txt").unwrap_or_default();

    // 1. Generate bigrams
    let en_bigrams = build_bigram_table_mapped(&en_text, 26, |c| {
        let d = (c as u32).checked_sub('a' as u32)? as usize;
        if d < 26 { Some(d) } else { None }
    });
    let ru_bigrams = build_bigram_table_mapped(&ru_text, 32, |c| {
        let lc = if c == 'ё' { 'е' } else { c };
        let d = (lc as u32).checked_sub('а' as u32)? as usize;
        if d < 32 { Some(d) } else { None }
    });
    let ua_bigrams = build_bigram_table_mapped(&ua_text, 33, char_to_ua_index);

    // 1b. Generate trigrams
    let en_trigrams = build_trigram_table_mapped(&en_text, 26, |c| {
        let d = (c as u32).checked_sub('a' as u32)? as usize;
        if d < 26 { Some(d) } else { None }
    });
    let ru_trigrams = build_trigram_table_mapped(&ru_text, 32, |c| {
        let lc = if c == 'ё' { 'е' } else { c };
        let d = (lc as u32).checked_sub('а' as u32)? as usize;
        if d < 32 { Some(d) } else { None }
    });
    let ua_trigrams = build_trigram_table_mapped(&ua_text, 33, char_to_ua_index);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    
    let bigrams_path = std::path::Path::new(&out_dir).join("bigrams_gen.rs");
    let mut f_bi = std::fs::File::create(&bigrams_path).expect("cannot create bigrams_gen.rs");
    writeln!(f_bi, "// Auto-generated by build.rs — do not edit manually.").expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static EN_BIGRAMS: [f32; {}] = {};", en_bigrams.len(), fmt_f32_array(&en_bigrams)).expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static RU_BIGRAMS: [f32; {}] = {};", ru_bigrams.len(), fmt_f32_array(&ru_bigrams)).expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static UA_BIGRAMS: [f32; {}] = {};", ua_bigrams.len(), fmt_f32_array(&ua_bigrams)).expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static EN_TRIGRAMS: [f32; {}] = {};", en_trigrams.len(), fmt_f32_array(&en_trigrams)).expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static RU_TRIGRAMS: [f32; {}] = {};", ru_trigrams.len(), fmt_f32_array(&ru_trigrams)).expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static UA_TRIGRAMS: [f32; {}] = {};", ua_trigrams.len(), fmt_f32_array(&ua_trigrams)).expect("write failed");

    // 2. Generate common dictionaries
    let mut en_words = get_common_words_mapped(&en_text, 3000, |c| {
        let d = (c as u32).checked_sub('a' as u32)? as usize;
        if d < 26 { Some(d) } else { None }
    });
    // Tech abbreviations with unusual bigram transitions (j→consonant, x-ending)
    // that score poorly under the EN model but are valid EN sequences.
    // "jpeg" is a confirmed false-positive: score_en=-13.11 because j→p is
    // almost absent from general-text corpora, letting Cyrillic scores win.
    for w in &[
        "bulk", "docx", "jpeg", "jira", "jest", "json", "jwt",
        "pptx", "xlsx",
    ] {
        if !en_words.contains(&w.to_string()) {
            en_words.push(w.to_string());
        }
    }
    en_words.sort();
    let mut ru_words = get_common_words_mapped(&ru_text, 5000, |c| {
        let lc = if c == 'ё' { 'е' } else { c };
        let d = (lc as u32).checked_sub('а' as u32)? as usize;
        if d < 32 { Some(d) } else { None }
    });
    // Guarantee that high-frequency everyday words are always dictionary-protected
    // even when the corpus has too few examples to rank them in the top N.
    // These are either inflected forms rarely seen in text corpora, or words
    // that are easily confused with Ukrainian equivalents.
    for w in &[
        // Common everyday words
        "давай", "иногда", "куда", "нужно", "сейчас", "сюда",
        "теперь", "тогда", "туда",
        // Russian-only forms (ы/э/ъ/ё markers — protect from false UA switch)
        "были", "было", "быть", "вышел", "вышла", "давно", "делал",
        "делать", "думал", "думать", "ехать", "жить", "знать",
        "идти", "играть", "купить", "любить", "менять", "мочь",
        "начать", "писать", "работать", "сказать", "слышать",
        "стоять", "хотеть", "читать",
        // Common inflected verb/noun endings unique to RU
        "смотришь", "говоришь", "знаешь", "думаешь", "можешь",
        "хочешь", "понимаешь", "слышишь",
        // Russian preposition+case forms
        "между", "через", "около", "перед",
    ] {
        if !ru_words.contains(&w.to_string()) {
            ru_words.push(w.to_string());
        }
    }
    ru_words.sort();
    let ua_words = get_common_words_mapped(&ua_text, 3000, char_to_ua_index);

    let dict_path = std::path::Path::new(&out_dir).join("dictionaries_gen.rs");
    let mut f_dict = std::fs::File::create(&dict_path).expect("cannot create dictionaries_gen.rs");
    writeln!(f_dict, "// Auto-generated by build.rs — do not edit manually.").expect("write failed");
    
    writeln!(f_dict, "pub static EN_COMMON_WORDS: &[&str] = &[").expect("write failed");
    for w in en_words {
        writeln!(f_dict, "    \"{}\",", w).expect("write failed");
    }
    writeln!(f_dict, "];").expect("write failed");

    writeln!(f_dict, "pub static RU_COMMON_WORDS: &[&str] = &[").expect("write failed");
    for w in ru_words {
        writeln!(f_dict, "    \"{}\",", w).expect("write failed");
    }
    writeln!(f_dict, "];").expect("write failed");

    writeln!(f_dict, "pub static UA_COMMON_WORDS: &[&str] = &[").expect("write failed");
    for w in ua_words {
        writeln!(f_dict, "    \"{}\",", w).expect("write failed");
    }
    writeln!(f_dict, "];").expect("write failed");
}

fn char_to_ua_index(c: char) -> Option<usize> {
    match c {
        'а' => Some(0),
        'б' => Some(1),
        'в' => Some(2),
        'г' => Some(3),
        'ґ' => Some(4),
        'д' => Some(5),
        'е' => Some(6),
        'є' => Some(7),
        'ж' => Some(8),
        'з' => Some(9),
        'и' => Some(10),
        'і' => Some(11),
        'ї' => Some(12),
        'й' => Some(13),
        'к' => Some(14),
        'л' => Some(15),
        'м' => Some(16),
        'н' => Some(17),
        'о' => Some(18),
        'п' => Some(19),
        'р' => Some(20),
        'с' => Some(21),
        'т' => Some(22),
        'у' => Some(23),
        'ф' => Some(24),
        'х' => Some(25),
        'ц' => Some(26),
        'ч' => Some(27),
        'ш' => Some(28),
        'щ' => Some(29),
        'ь' => Some(30),
        'ю' => Some(31),
        'я' => Some(32),
        _ => None,
    }
}

fn build_bigram_table_mapped(text: &str, n: usize, char_map: impl Fn(char) -> Option<usize>) -> Vec<f32> {
    let indices: Vec<usize> = text
        .chars()
        .filter_map(|c| {
            let lc = c.to_lowercase().next()?;
            char_map(lc)
        })
        .collect();

    let mut counts = vec![0u32; n * n];
    for w in indices.windows(2) {
        counts[w[0] * n + w[1]] += 1;
    }

    // Laplace (add-1) smoothing
    let total: u64 = counts.iter().map(|&c| c as u64).sum::<u64>() + (n * n) as u64;
    counts.iter().map(|&c| (c + 1) as f32 / total as f32).collect()
}

fn get_common_words_mapped(text: &str, limit: usize, char_map: impl Fn(char) -> Option<usize>) -> Vec<String> {
    use std::collections::HashMap;
    let mut counts = HashMap::new();

    let mut current_word = String::new();
    for c in text.chars() {
        if c.is_alphabetic() {
            let lc = c.to_lowercase().next().unwrap_or(c);
            if char_map(lc).is_some() {
                current_word.push(lc);
            } else {
                if !current_word.is_empty() {
                    *counts.entry(current_word.clone()).or_insert(0u64) += 1;
                    current_word.clear();
                }
            }
        } else {
            if !current_word.is_empty() {
                *counts.entry(current_word.clone()).or_insert(0u64) += 1;
                current_word.clear();
            }
        }
    }
    if !current_word.is_empty() {
        *counts.entry(current_word).or_insert(0u64) += 1;
    }

    let mut words: Vec<(String, u64)> = counts
        .into_iter()
        .filter(|(w, _)| w.chars().count() >= 4)
        .collect();

    words.sort_by(|a, b| b.1.cmp(&a.1));

    let mut top_words: Vec<String> = words.into_iter().take(limit).map(|(w, _)| w).collect();
    top_words.sort();
    top_words
}

fn fmt_f32_array(v: &[f32]) -> String {
    let entries: Vec<String> = v.iter().map(|&x| format!("{:.10}f32", x)).collect();
    format!("[{}]", entries.join(", "))
}

fn build_trigram_table_mapped(text: &str, n: usize, char_map: impl Fn(char) -> Option<usize>) -> Vec<f32> {
    let indices: Vec<usize> = text
        .chars()
        .filter_map(|c| {
            let lc = c.to_lowercase().next()?;
            char_map(lc)
        })
        .collect();

    let mut counts = vec![0u32; n * n * n];
    for w in indices.windows(3) {
        counts[w[0] * n * n + w[1] * n + w[2]] += 1;
    }

    // Laplace (add-1) smoothing
    let total: u64 = counts.iter().map(|&c| c as u64).sum::<u64>() + (n * n * n) as u64;
    counts.iter().map(|&c| (c + 1) as f32 / total as f32).collect()
}
