fn main() {
    generate_language_models();
    tauri_build::build();
}

fn generate_language_models() {
    use std::io::Write as _;

    println!("cargo:rerun-if-changed=../corpus/ru.txt");
    println!("cargo:rerun-if-changed=../corpus/en.txt");

    let ru_text = std::fs::read_to_string("../corpus/ru.txt").unwrap_or_default();
    let en_text = std::fs::read_to_string("../corpus/en.txt").unwrap_or_default();

    // 1. Generate bigrams
    let ru_bigrams = build_bigram_table(&ru_text, 'а', 32, |c| if c == 'ё' { 'е' } else { c });
    let en_bigrams = build_bigram_table(&en_text, 'a', 26, |c| c);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    
    let bigrams_path = std::path::Path::new(&out_dir).join("bigrams_gen.rs");
    let mut f_bi = std::fs::File::create(&bigrams_path).expect("cannot create bigrams_gen.rs");
    writeln!(f_bi, "// Auto-generated by build.rs — do not edit manually.").expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static EN_BIGRAMS: [f32; {}] = {};", en_bigrams.len(), fmt_f32_array(&en_bigrams)).expect("write failed");
    writeln!(f_bi, "#[allow(clippy::excessive_precision)]").expect("write failed");
    writeln!(f_bi, "pub static RU_BIGRAMS: [f32; {}] = {};", ru_bigrams.len(), fmt_f32_array(&ru_bigrams)).expect("write failed");

    // 2. Generate common dictionaries
    let ru_words = get_common_words(&ru_text, 'а', 32, |c| if c == 'ё' { 'е' } else { c });
    let en_words = get_common_words(&en_text, 'a', 26, |c| c);

    let dict_path = std::path::Path::new(&out_dir).join("dictionaries_gen.rs");
    let mut f_dict = std::fs::File::create(&dict_path).expect("cannot create dictionaries_gen.rs");
    writeln!(f_dict, "// Auto-generated by build.rs — do not edit manually.").expect("write failed");
    writeln!(f_dict, "pub static EN_COMMON_WORDS: &[&str] = &[").expect("write failed");
    for w in en_words {
        writeln!(f_dict, "    \"{}\",", w).expect("write failed");
    }
    writeln!(f_dict, "];").expect("write failed");

    writeln!(f_dict, "pub static RU_COMMON_WORDS: &[&str] = &[").expect("write failed");
    for w in ru_words {
        writeln!(f_dict, "    \"{}\",", w).expect("write failed");
    }
    writeln!(f_dict, "];").expect("write failed");
}

fn build_bigram_table(text: &str, base: char, n: usize, norm: impl Fn(char) -> char) -> Vec<f32> {
    let base_u = base as u32;
    let indices: Vec<usize> = text
        .chars()
        .filter_map(|c| {
            let lc = norm(c.to_lowercase().next()?);
            let d = (lc as u32).checked_sub(base_u)? as usize;
            if d < n { Some(d) } else { None }
        })
        .collect();

    let mut counts = vec![0u32; n * n];
    for w in indices.windows(2) {
        counts[w[0] * n + w[1]] += 1;
    }

    // Laplace (add-1) smoothing
    let total: u64 = counts.iter().map(|&c| c as u64).sum::<u64>() + (n * n) as u64;
    counts.iter().map(|&c| (c + 1) as f32 / total as f32).collect()
}

fn get_common_words(text: &str, base: char, n: usize, norm: impl Fn(char) -> char) -> Vec<String> {
    use std::collections::HashMap;
    let mut counts = HashMap::new();
    let base_u = base as u32;

    let mut current_word = String::new();
    for c in text.chars() {
        if c.is_alphabetic() {
            let lc = norm(c.to_lowercase().next().unwrap_or(c));
            let d = (lc as u32).checked_sub(base_u);
            if let Some(d) = d {
                if d < n as u32 {
                    current_word.push(lc);
                } else {
                    if !current_word.is_empty() {
                        *counts.entry(current_word.clone()).or_insert(0u64) += 1;
                        current_word.clear();
                    }
                }
            } else {
                if !current_word.is_empty() {
                    *counts.entry(current_word.clone()).or_insert(0u64) += 1;
                    current_word.clear();
                }
            }
        } else {
            if !current_word.is_empty() {
                *counts.entry(current_word.clone()).or_insert(0u64) += 1;
                current_word.clear();
            }
        }
    }
    if !current_word.is_empty() {
        *counts.entry(current_word).or_insert(0u64) += 1;
    }

    let mut words: Vec<(String, u64)> = counts
        .into_iter()
        .filter(|(w, _)| w.chars().count() >= 4)
        .collect();

    words.sort_by(|a, b| b.1.cmp(&a.1));

    let mut top_words: Vec<String> = words.into_iter().take(3000).map(|(w, _)| w).collect();
    top_words.sort();
    top_words
}

fn fmt_f32_array(v: &[f32]) -> String {
    let entries: Vec<String> = v.iter().map(|&x| format!("{:.10}f32", x)).collect();
    format!("[{}]", entries.join(", "))
}
