fn main() {
    generate_bigrams();
    tauri_build::build();
}

fn generate_bigrams() {
    use std::io::Write as _;

    println!("cargo:rerun-if-changed=../corpus/ru.txt");
    println!("cargo:rerun-if-changed=../corpus/en.txt");

    let ru_text = std::fs::read_to_string("../corpus/ru.txt").unwrap_or_default();
    let en_text = std::fs::read_to_string("../corpus/en.txt").unwrap_or_default();

    // Russian: а-я = U+0430..U+044F, 32 letters.  ё → е normalisation applied.
    let ru = build_table(&ru_text, 'а', 32, |c| if c == 'ё' { 'е' } else { c });
    // English: a-z, 26 letters.
    let en = build_table(&en_text, 'a', 26, |c| c);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = std::path::Path::new(&out_dir).join("bigrams_gen.rs");
    let mut f = std::fs::File::create(&out_path).expect("cannot create bigrams_gen.rs");

    writeln!(f, "// Auto-generated by build.rs — do not edit manually.").unwrap();
    writeln!(f, "#[allow(clippy::excessive_precision)]").unwrap();
    writeln!(f, "pub static EN_BIGRAMS: [f32; {}] = {};", en.len(), fmt_f32_array(&en)).unwrap();
    writeln!(f, "#[allow(clippy::excessive_precision)]").unwrap();
    writeln!(f, "pub static RU_BIGRAMS: [f32; {}] = {};", ru.len(), fmt_f32_array(&ru)).unwrap();
}

fn build_table(text: &str, base: char, n: usize, norm: impl Fn(char) -> char) -> Vec<f32> {
    let base_u = base as u32;
    let indices: Vec<usize> = text
        .chars()
        .filter_map(|c| {
            let lc = norm(c.to_lowercase().next()?);
            let d = (lc as u32).checked_sub(base_u)? as usize;
            if d < n { Some(d) } else { None }
        })
        .collect();

    let mut counts = vec![0u32; n * n];
    for w in indices.windows(2) {
        counts[w[0] * n + w[1]] += 1;
    }

    // Laplace (add-1) smoothing — every bigram gets probability > 0.
    let total: u64 = counts.iter().map(|&c| c as u64).sum::<u64>() + (n * n) as u64;
    counts.iter().map(|&c| (c + 1) as f32 / total as f32).collect()
}

fn fmt_f32_array(v: &[f32]) -> String {
    let entries: Vec<String> = v.iter().map(|&x| format!("{:.10}f32", x)).collect();
    format!("[{}]", entries.join(", "))
}
