fn main() {
    generate_bigrams();

    if std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default() != "windows" {
        return;
    }

    winresource::WindowsResource::new()
        .set_manifest(MANIFEST)
        .compile()
        .expect("failed to compile Windows resources");
}

// ── Bigram frequency table generator ─────────────────────────────────────────
//
// Reads corpus/ru.txt and corpus/en.txt, counts adjacent letter pairs, applies
// Laplace (add-1) smoothing, and emits normalised f32 probability tables to
// $OUT_DIR/bigrams_gen.rs.  Included by src/bigrams.rs via include!().

fn generate_bigrams() {
    use std::io::Write as _;

    println!("cargo:rerun-if-changed=corpus/ru.txt");
    println!("cargo:rerun-if-changed=corpus/en.txt");

    let ru_text = std::fs::read_to_string("corpus/ru.txt").unwrap_or_default();
    let en_text = std::fs::read_to_string("corpus/en.txt").unwrap_or_default();

    // Russian: а-я = U+0430..U+044F, 32 letters.  ё → е normalisation applied.
    let ru = build_table(&ru_text, 'а', 32, |c| if c == 'ё' { 'е' } else { c });
    // English: a-z, 26 letters.
    let en = build_table(&en_text, 'a', 26, |c| c);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = std::path::Path::new(&out_dir).join("bigrams_gen.rs");
    let mut f = std::fs::File::create(&out_path).expect("cannot create bigrams_gen.rs");

    writeln!(f, "// Auto-generated by build.rs — do not edit manually.").unwrap();
    writeln!(f, "pub static EN_BIGRAMS: [f32; {}] = {};", en.len(), fmt_f32_array(&en)).unwrap();
    writeln!(f, "pub static RU_BIGRAMS: [f32; {}] = {};", ru.len(), fmt_f32_array(&ru)).unwrap();
}

fn build_table(text: &str, base: char, n: usize, norm: impl Fn(char) -> char) -> Vec<f32> {
    let base_u = base as u32;
    let indices: Vec<usize> = text
        .chars()
        .filter_map(|c| {
            let lc = norm(c.to_lowercase().next()?);
            let d = (lc as u32).checked_sub(base_u)? as usize;
            if d < n { Some(d) } else { None }
        })
        .collect();

    let mut counts = vec![0u32; n * n];
    for w in indices.windows(2) {
        counts[w[0] * n + w[1]] += 1;
    }

    // Laplace (add-1) smoothing — every bigram gets probability > 0.
    let total: u64 = counts.iter().map(|&c| c as u64).sum::<u64>() + (n * n) as u64;
    counts.iter().map(|&c| (c + 1) as f32 / total as f32).collect()
}

fn fmt_f32_array(v: &[f32]) -> String {
    let entries: Vec<String> = v.iter().map(|&x| format!("{:.10}f32", x)).collect();
    format!("[{}]", entries.join(", "))
}

const MANIFEST: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">

  <!-- Tell Windows which OS versions this app explicitly supports.
       Required for correct DPI scaling, theming, and API behaviour on Win10/11. -->
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/> <!-- Windows 10 / 11 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/> <!-- Windows 8.1 -->
    </application>
  </compatibility>

  <!-- Request Common Controls v6 (comctl32.dll version 6).
       Without this Windows silently uses v5, which lacks TaskDialogIndirect
       and the visual styles required by tray-icon and eframe. -->
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"/>
    </dependentAssembly>
  </dependency>

  <!-- Per-monitor DPI awareness v2: crisp UI on high-DPI / mixed-DPI setups. -->
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        PerMonitorV2
      </dpiAwareness>
    </windowsSettings>
  </application>

</assembly>"#;
